import { Router } from 'express';
import { authController } from './auth.controller';
import { authenticate } from '../../middleware/authenticate';
import { validate } from '../../middleware/validate';
import { authRateLimiter, passwordResetLimiter } from '../../middleware/rateLimiter';
import { RegisterSchema, LoginSchema, ForgotPasswordSchema, ResetPasswordSchema, ChangePasswordSchema, VerifyEmailSchema } from './auth.validation';
const router = Router();
router.post('/register', authRateLimiter, validate(RegisterSchema), authController.register);
router.post('/login', authRateLimiter, validate(LoginSchema), authController.login);
router.post('/logout', authenticate, authController.logout);
router.post('/logout-all', authenticate, authController.logoutAll);
router.post('/refresh', authController.refresh);
router.post('/verify-email', validate(VerifyEmailSchema), authController.verifyEmail);
router.post('/resend-verification', authenticate, authController.resendVerification);
router.post('/forgot-password', passwordResetLimiter, validate(ForgotPasswordSchema), authController.forgotPassword);
router.post('/reset-password', validate(ResetPasswordSchema), authController.resetPassword);
router.post('/change-password', authenticate, validate(ChangePasswordSchema), authController.changePassword);
router.get('/sessions', authenticate, authController.getSessions);
router.delete('/sessions/:id', authenticate, authController.revokeSession);
export default router;
